<?php
if (!defined('ABSPATH')) { exit; }
class GPSUMA_Frontend {
 public function __construct(){ add_shortcode('gpsuma_area_cliente',array($this,'area_cliente')); add_action('wp_enqueue_scripts',array($this,'assets')); }
 public function assets(){ if(!is_singular())return; global $post; if($post&&has_shortcode($post->post_content,'gpsuma_area_cliente')) wp_enqueue_style('gpsuma-frontend',GPSUMA_URL.'assets/css/frontend.css',array(),GPSUMA_VERSION); }

 private function normalize_ticket_uploads() {
  $nonce = isset( $_POST['gpsuma_richiesta_nonce'] ) ? sanitize_text_field( wp_unslash( $_POST['gpsuma_richiesta_nonce'] ) ) : '';
  if ( ! $nonce || ! wp_verify_nonce( $nonce, 'gpsuma_invia_richiesta' ) ) { return array(); }
  if ( empty( $_FILES['allegati'] ) || ! is_array( $_FILES['allegati'] ) ) { return array(); }
  // phpcs:disable WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Upload metadata is validated and passed to WordPress media_handle_upload(), which performs MIME and file validation.
  $group = $_FILES['allegati'];
  // phpcs:enable WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
  $required = array( 'name', 'type', 'tmp_name', 'error', 'size' );
  foreach ( $required as $field ) { if ( ! isset( $group[$field] ) || ! is_array( $group[$field] ) ) { return array(); } }
  $files = array();
  foreach ( array_keys( $group['name'] ) as $key ) {
   if ( ! isset( $group['name'][$key], $group['type'][$key], $group['tmp_name'][$key], $group['error'][$key], $group['size'][$key] ) ) { continue; }
   $name = sanitize_file_name( wp_unslash( $group['name'][$key] ) );
   if ( '' === $name ) { continue; }
   $files[] = array(
    'name' => $name,
    'type' => sanitize_mime_type( wp_unslash( $group['type'][$key] ) ),
    'tmp_name' => sanitize_text_field( wp_unslash( $group['tmp_name'][$key] ) ),
    'error' => absint( $group['error'][$key] ),
    'size' => absint( $group['size'][$key] ),
   );
  }
  return $files;
 }

 public function area_cliente(){
  if(!is_user_logged_in()){ ob_start(); ?><div class="gpsuma-portal gpsuma-portal-login"><?php if(has_custom_logo()): ?><div class="gpsuma-login-brand"><?php echo wp_kses_post( get_custom_logo() ); ?></div><?php endif; ?><span class="gpsuma-eyebrow">Portale clienti</span><h2>Area assistenza</h2><p>Accedi con le credenziali ricevute per consultare dispositivi, interventi, pacchetti e richieste.</p><?php wp_login_form(array('redirect'=>get_permalink(),'label_username'=>'Email o nome utente','label_password'=>'Password','label_remember'=>'Ricordami','label_log_in'=>'Accedi','remember'=>true)); ?></div><?php return ob_get_clean(); }
  $db=new GPSUMA_DB(); $uid=get_current_user_id();
  $c=$db->get_portal_customer($uid);
  if(!$c)return '<div class="gpsuma-portal gpsuma-alert">Il tuo account non è ancora associato a un cliente. Contatta l’assistenza.</div>';
  $request_notice='';
  if(isset($_POST['gpsuma_invia_richiesta']) && isset($_POST['gpsuma_richiesta_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['gpsuma_richiesta_nonce'])),'gpsuma_invia_richiesta')){
   $oggetto=sanitize_text_field(wp_unslash($_POST['oggetto']??'')); $descrizione=sanitize_textarea_field(wp_unslash($_POST['descrizione']??'')); $dispositivo_id=absint($_POST['dispositivo_id']??0); $priorita=sanitize_text_field(wp_unslash($_POST['priorita']??'Normale'));
   $device=$dispositivo_id?$db->get_portal_device($dispositivo_id,$c->id):null; $dispositivo=$device?trim($device->tipo.' '.$device->marca.' '.$device->modello):'';
   if($oggetto && $descrizione && in_array($priorita,array('Bassa','Normale','Alta','Urgente'),true)){ $ticket_id=$db->create_portal_ticket(array('cliente_id'=>$c->id,'oggetto'=>$oggetto,'descrizione'=>$descrizione,'dispositivo'=>$dispositivo,'dispositivo_id'=>$dispositivo_id?:null,'priorita'=>$priorita,'stato'=>'Nuovo','data_creazione'=>current_time('mysql'))); if($ticket_id){ foreach ( $this->normalize_ticket_uploads() as $upload ) { require_once ABSPATH . 'wp-admin/includes/file.php'; require_once ABSPATH . 'wp-admin/includes/media.php'; require_once ABSPATH . 'wp-admin/includes/image.php'; $_FILES['gpsuma_single_file'] = $upload; $aid = media_handle_upload( 'gpsuma_single_file', 0 ); if ( ! is_wp_error( $aid ) ) { $db->add_ticket_attachment( $ticket_id, $aid ); } } unset( $_FILES['gpsuma_single_file'] ); wp_mail(get_option('admin_email'),'Nuovo ticket #'.$ticket_id.' - '.$oggetto,"Cliente: {$c->nome}
Priorità: {$priorita}

{$descrizione}"); $request_notice='<div class="gpsuma-success">Ticket #'.$ticket_id.' inviato correttamente.</div>'; } else $request_notice='<div class="gpsuma-alert">Non è stato possibile inviare il ticket.</div>'; } else { $request_notice='<div class="gpsuma-alert">Compila oggetto e descrizione.</div>'; }
  }
  if(isset($_POST['gpsuma_commenta_ticket']) && isset($_POST['gpsuma_commento_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['gpsuma_commento_nonce'])),'gpsuma_commenta_ticket')){
   $ticket_id=absint($_POST['ticket_id']??0); $messaggio=sanitize_textarea_field(wp_unslash($_POST['messaggio']??'')); $owned=$db->portal_ticket_belongs_to_customer($ticket_id,$c->id);
   if($owned && $messaggio){ $u=wp_get_current_user(); $db->add_portal_ticket_comment(array('richiesta_id'=>$ticket_id,'autore_user_id'=>$uid,'autore_nome'=>$u->display_name?:$c->nome,'tipo_autore'=>'cliente','messaggio'=>$messaggio,'visibile_cliente'=>1,'data_creazione'=>current_time('mysql'))); $db->touch_ticket($ticket_id); wp_mail(get_option('admin_email'),'Nuovo commento ticket #'.$ticket_id,$messaggio); $request_notice='<div class="gpsuma-success">Commento inviato.</div>'; }
  }
  $portal=$db->get_portal_data($c->id);
  $ds=$portal['devices']; $ps=$portal['packages']; $contracts=$portal['contracts']; $qs=$portal['tickets']; $is=$portal['interventions']; $attachments=$portal['intervention_attachments']; $deadlines=$portal['deadlines']; $ticket_comments=$portal['ticket_comments']; $ticket_attachments=$portal['ticket_attachments'];
  ob_start(); ?><div class="gpsuma-portal"><div class="gpsuma-portal-header"><div class="gpsuma-brand-row"><?php if(has_custom_logo()): ?><div class="gpsuma-brand-logo"><?php echo wp_kses_post( get_custom_logo() ); ?></div><?php endif; ?><div><span class="gpsuma-eyebrow">Area riservata</span><h2>Benvenuto, <?php echo esc_html($c->nome); ?></h2></div></div><a class="gpsuma-logout" href="<?php echo esc_url(wp_logout_url(get_permalink())); ?>">Esci</a></div>
  <nav class="gpsuma-portal-nav" aria-label="Navigazione area cliente"><a href="#gpsuma-dati">I tuoi dati</a><a href="#gpsuma-dispositivi">Dispositivi</a><?php if($ps): ?><a href="#gpsuma-pacchetti">Pacchetti</a><?php endif; ?><?php if($contracts): ?><a href="#gpsuma-contratti">Contratti</a><?php endif; ?><?php if($deadlines): ?><a href="#gpsuma-scadenze">Scadenze</a><?php endif; ?><a href="#gpsuma-richieste">Richiedi assistenza</a><a href="#gpsuma-interventi">Interventi</a></nav>
  <?php echo wp_kses_post( $request_notice ); ?>
  <div class="gpsuma-portal-stats"><div><strong><?php echo count($ds); ?></strong><span>Dispositivi</span></div><div><strong><?php echo count($is); ?></strong><span>Interventi</span></div><div><strong><?php echo count($qs); ?></strong><span>Ticket</span></div><div><strong><?php echo count($ps); ?></strong><span>Pacchetti</span></div><div><strong><?php echo count($contracts); ?></strong><span>Contratti</span></div></div>
  <div class="gpsuma-portal-grid"><section id="gpsuma-dati" class="gpsuma-panel"><h3>I tuoi dati</h3><dl class="gpsuma-data-list"><div><dt>Email</dt><dd><?php echo esc_html($c->email?:'—'); ?></dd></div><div><dt>Telefono</dt><dd><?php echo esc_html($c->telefono?:'—'); ?></dd></div><div><dt>Indirizzo</dt><dd><?php echo nl2br(esc_html($c->indirizzo?:'—')); ?></dd></div></dl></section>
  <section id="gpsuma-dispositivi" class="gpsuma-panel"><div class="gpsuma-panel-title"><h3>I tuoi dispositivi</h3><span class="gpsuma-count"><?php echo count($ds); ?></span></div><div class="gpsuma-device-list"><?php if(!$ds): ?><p>Nessun dispositivo associato.</p><?php endif; foreach($ds as $d): ?><article class="gpsuma-device-card"><span class="gpsuma-device-icon">💻</span><div><h4><?php echo esc_html(trim($d->tipo.' '.$d->marca.' '.$d->modello)); ?></h4><span class="gpsuma-device-status gpsuma-device-status-<?php echo esc_attr(sanitize_title($d->stato ?: 'Operativo')); ?>"><?php echo esc_html($d->stato ?: 'Operativo'); ?></span><p><strong>Seriale:</strong> <?php echo esc_html($d->seriale?:'—'); ?></p><p><strong>Sistema:</strong> <?php echo esc_html($d->sistema?:'—'); ?></p></div></article><?php endforeach; ?></div></section></div>
  <?php if($ps): ?><section id="gpsuma-pacchetti" class="gpsuma-panel gpsuma-packages"><div class="gpsuma-panel-title"><h3>Pacchetti assistenza</h3><span class="gpsuma-count"><?php echo count($ps); ?></span></div><div class="gpsuma-package-list"><?php foreach($ps as $p): $used=(int)$p->utilizzati; $unlimited=!empty($p->interventi_illimitati); $total=(int)$p->interventi_inclusi; $remaining=$unlimited?null:max(0,$total-$used); $percent=(!$unlimited&&$total)?min(100,round($used/$total*100)):0; ?><article class="gpsuma-package-card"><div class="gpsuma-package-top"><div><h4><?php echo esc_html($p->nome); ?></h4><span class="gpsuma-package-status"><?php echo esc_html($p->stato); ?></span></div><strong><?php echo $unlimited ? '∞ Illimitati' : esc_html($remaining).' residui'; ?></strong></div><div class="gpsuma-package-numbers"><span><?php echo esc_html($used); ?> utilizzati</span><span><?php echo $unlimited ? 'Nessun limite' : esc_html($total).' inclusi'; ?></span></div><?php if(!$unlimited): ?><div class="gpsuma-frontend-progress"><span style="width:<?php echo esc_attr($percent); ?>%"></span></div><?php endif; ?><?php if($p->data_scadenza): ?><p class="gpsuma-package-expiry">Scadenza: <?php echo esc_html(date_i18n('d/m/Y',strtotime($p->data_scadenza))); ?></p><?php endif; ?></article><?php endforeach; ?></div></section><?php endif; ?>
  <?php if($contracts): ?><section id="gpsuma-contratti" class="gpsuma-panel gpsuma-packages"><div class="gpsuma-panel-title"><h3>Contratti di assistenza</h3><span class="gpsuma-count"><?php echo count($contracts); ?></span></div><div class="gpsuma-package-list"><?php foreach($contracts as $contract): $hours=round((float)$contract->minuti_usati/60,2); $unlimited=!empty($contract->interventi_illimitati); $remaining_interventions=$unlimited?null:max(0,(int)$contract->interventi_inclusi-(int)$contract->interventi_usati); ?><article class="gpsuma-package-card"><div class="gpsuma-package-top"><div><h4><?php echo esc_html($contract->nome); ?></h4><span class="gpsuma-package-status"><?php echo esc_html($contract->stato.' · '.$contract->tipo); ?></span></div><strong><?php echo esc_html(number_format_i18n((float)$contract->valore_contratto,2).' €'); ?></strong></div><div class="gpsuma-package-numbers"><span>Dal <?php echo esc_html(date_i18n('d/m/Y',strtotime($contract->data_inizio))); ?></span><span><?php echo $contract->data_fine?'Al '.esc_html(date_i18n('d/m/Y',strtotime($contract->data_fine))):'Senza scadenza'; ?></span></div><?php if((float)$contract->ore_incluse>0): ?><p><strong>Ore:</strong> <?php echo esc_html($hours.' / '.$contract->ore_incluse); ?> utilizzate</p><?php endif; ?><?php if($unlimited): ?><p><strong>Interventi:</strong> ∞ Illimitati (<?php echo esc_html((int)$contract->interventi_usati); ?> registrati)</p><?php elseif((int)$contract->interventi_inclusi>0): ?><p><strong>Interventi:</strong> <?php echo esc_html((int)$contract->interventi_usati.' / '.(int)$contract->interventi_inclusi); ?> — <?php echo esc_html($remaining_interventions); ?> residui</p><?php endif; ?><?php if($contract->servizi_inclusi): ?><p><strong>Servizi inclusi:</strong><br><?php echo nl2br(esc_html($contract->servizi_inclusi)); ?></p><?php endif; ?><?php if($contract->esclusioni): ?><p><strong>Esclusioni:</strong><br><?php echo nl2br(esc_html($contract->esclusioni)); ?></p><?php endif; ?></article><?php endforeach; ?></div></section><?php endif; ?>
  <?php if($deadlines): ?><section id="gpsuma-scadenze" class="gpsuma-panel gpsuma-deadlines"><div class="gpsuma-panel-title"><h3>Scadenze</h3><span class="gpsuma-count"><?php echo count($deadlines); ?></span></div><div class="gpsuma-deadline-list"><?php foreach($deadlines as $sc): $days=(int)floor((strtotime($sc->data_scadenza)-strtotime(current_time('Y-m-d')))/DAY_IN_SECONDS); ?><article class="<?php echo $days<0?'is-expired':($days<=(int)$sc->preavviso_giorni?'is-due':''); ?>"><div><strong><?php echo esc_html($sc->titolo); ?></strong><span><?php echo esc_html($sc->tipo); ?><?php if($sc->dispositivo_nome): ?> · <?php echo esc_html($sc->dispositivo_nome); ?><?php endif; ?></span></div><div><strong><?php echo esc_html(date_i18n('d/m/Y',strtotime($sc->data_scadenza))); ?></strong><small><?php echo $days<0?esc_html('Scaduta da '.abs($days).' giorni'):esc_html('Tra '.$days.' giorni'); ?></small></div></article><?php endforeach; ?></div></section><?php endif; ?>
  <section id="gpsuma-richieste" class="gpsuma-panel gpsuma-requests"><div class="gpsuma-panel-title"><h3>Richiedi assistenza</h3><span class="gpsuma-count">Nuova</span></div>
  <form method="post" enctype="multipart/form-data" class="gpsuma-request-form">
   <?php wp_nonce_field('gpsuma_invia_richiesta','gpsuma_richiesta_nonce'); ?>
   <div><label>Oggetto *</label><input type="text" name="oggetto" required maxlength="200" placeholder="Es. Stampante non raggiungibile"></div>
   <div><label>Dispositivo</label><select name="dispositivo_id"><option value="">Nessun dispositivo specifico</option><?php foreach($ds as $d): $dn=trim($d->tipo.' '.$d->marca.' '.$d->modello); ?><option value="<?php echo (int)$d->id; ?>"><?php echo esc_html($dn); ?></option><?php endforeach; ?></select></div>
   <div><label>Priorità</label><select name="priorita"><option>Bassa</option><option selected>Normale</option><option>Alta</option><option>Urgente</option></select></div>
   <div class="gpsuma-request-description"><label>Descrizione *</label><textarea name="descrizione" rows="5" required placeholder="Descrivi il problema e quando si verifica..."></textarea></div><div class="gpsuma-request-description"><label>Allegati</label><input type="file" name="allegati[]" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt"><small>Puoi allegare foto, screenshot e documenti.</small></div>
   <button type="submit" name="gpsuma_invia_richiesta" value="1" class="gpsuma-primary-button">Invia richiesta</button>
  </form>
  <?php if($qs): ?><div class="gpsuma-my-requests"><h4>I tuoi ticket</h4><?php foreach($qs as $q): $comments=$ticket_comments[$q->id]??array(); $qatts=$ticket_attachments[$q->id]??array(); ?><article><div><span class="gpsuma-status-pill gpsuma-status-<?php echo esc_attr(sanitize_title($q->stato)); ?>"><?php echo esc_html($q->stato); ?></span><strong>#<?php echo (int)$q->id; ?> · <?php echo esc_html($q->oggetto); ?></strong><small><?php echo esc_html(date_i18n('d/m/Y H:i',strtotime($q->data_creazione))); ?></small></div><p><?php echo nl2br(esc_html($q->descrizione)); ?></p><?php if($qatts): ?><div class="gpsuma-frontend-attachments"><?php foreach($qatts as $a): $url=wp_get_attachment_url($a->attachment_id); ?><a href="<?php echo esc_url($url); ?>" target="_blank" rel="noopener">📎 <?php echo esc_html(get_the_title($a->attachment_id)?:basename((string)$url)); ?></a><?php endforeach; ?></div><?php endif; ?><?php if($comments): ?><div class="gpsuma-ticket-thread"><?php foreach($comments as $cm): ?><div class="gpsuma-ticket-message <?php echo $cm->tipo_autore==='tecnico'?'is-tech':'is-client'; ?>"><strong><?php echo esc_html($cm->autore_nome); ?></strong><small><?php echo esc_html(date_i18n('d/m/Y H:i',strtotime($cm->data_creazione))); ?></small><p><?php echo nl2br(esc_html($cm->messaggio)); ?></p></div><?php endforeach; ?></div><?php endif; ?><?php if($q->stato!=='Chiuso'): ?><form method="post" class="gpsuma-ticket-comment-form"><?php wp_nonce_field('gpsuma_commenta_ticket','gpsuma_commento_nonce'); ?><input type="hidden" name="ticket_id" value="<?php echo (int)$q->id; ?>"><textarea name="messaggio" rows="2" required placeholder="Aggiungi un messaggio..."></textarea><button class="gpsuma-primary-button" name="gpsuma_commenta_ticket" value="1">Invia messaggio</button></form><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
  </section>
  <section id="gpsuma-interventi" class="gpsuma-panel gpsuma-history"><div class="gpsuma-panel-title"><h3>Storico interventi</h3><span class="gpsuma-count"><?php echo count($is); ?></span></div><?php if(!$is): ?><p>Nessun intervento disponibile.</p><?php else: ?><div class="gpsuma-intervention-list"><?php foreach($is as $i): ?><article class="gpsuma-intervention-card"><div class="gpsuma-intervention-date"><strong><?php echo esc_html(date_i18n('d',strtotime($i->data_intervento))); ?></strong><span><?php echo esc_html(date_i18n('M Y',strtotime($i->data_intervento))); ?></span></div><div><h4><?php echo esc_html($i->tipo?:'Intervento tecnico'); ?></h4><p><?php echo nl2br(esc_html($i->descrizione)); ?></p><?php if($i->dispositivi): ?><p><strong>Dispositivi:</strong> <?php echo esc_html($i->dispositivi); ?></p><?php endif; ?><div class="gpsuma-meta"><?php if($i->tecnico): ?><span>Tecnico: <?php echo esc_html($i->tecnico); ?></span><?php endif; ?><?php if($i->durata_minuti): ?><span>Durata: <?php echo esc_html($i->durata_minuti); ?> min</span><?php endif; ?><span>Stato: <?php echo esc_html($i->stato); ?></span></div><?php if($i->materiale): ?><p><strong>Materiale:</strong> <?php echo nl2br(esc_html($i->materiale)); ?></p><?php endif; ?><?php if(!empty($attachments[$i->id])): ?><div class="gpsuma-frontend-attachments"><strong>Allegati</strong><?php foreach($attachments[$i->id] as $a): $url=wp_get_attachment_url($a->attachment_id); ?><a href="<?php echo esc_url($url); ?>" target="_blank" rel="noopener">📎 <?php echo esc_html(get_the_title($a->attachment_id)?:basename((string)$url)); ?></a><?php endforeach; ?></div><?php endif; ?></div></article><?php endforeach; ?></div><?php endif; ?></section></div><?php return ob_get_clean();
 }
}
